apps/fbis-ccf/behaviours/set-question.js
apps/fbis-ccf/fields/index.js
apps/fbis-ccf/index.js
apps/fbis-ccf/translations/src/en/buttons.json
apps/fbis-ccf/translations/src/en/fields.json
apps/fbis-ccf/translations/src/en/pages.json
apps/fbis-ccf/translations/src/en/validation.json
apps/fbis-ccf/views/landing.html
apps/fbis-ccf/views/query.html
apps/fbis-ccf/views/question.html
assets/scss/app.scss
assets/scss/custom.scss
test/add-location-to-backlin.spec.js
test/set-question.spec.js

https://collaboration.homeoffice.gov.uk/jira/browse/FBISCC-24
* Also covers FBISCC-7/25/26
* Adds interim page for user to choose what their technical problem is about
* Adds query page with templating for correct headers and fields based on technical problem
* Does not include email or UAN validation, awaiting business requirements
Add query and question pages
So that the user can select their technical problem and submit a query with the correct fields and content
Add query and question page templates in views directory. 'set-question' behaviour adds flags to values that are used by query template to load correct content and fields
Add tests in tests folder
Validation of email and UAN split into new tickets, awaiting business requirements. A ticket will also be created to spike an …

FBISCC-24: Add the query and question pages

---

apps/fbis-ccf/fields/index.js
apps/fbis-ccf/index.js
apps/fbis-ccf/translations/src/en/fields.json
apps/fbis-ccf/translations/src/en/pages.json
apps/fbis-ccf/translations/src/en/validation.json
apps/fbis-ccf/views/details.html
apps/fbis-ccf/views/query.html
apps/fbis-ccf/views/save-and-continue.html
assets/scss/custom.scss

Adds new pages to get users identity and collect representative's details.
So the SRC can respond to the representative rather than applicant to resolve the query if required.
Uses HOF fork approach in fbiscc/index.js to send user down correct route and additional labelling for text content on the query page.
No new behaviours added. Tested manually for now, awaiting automation testing approach.

FBISCC-33: Fork to collect representative's details if writing on behalf of someone else

---

apps/fbis-ccf/translations/src/en/fields.json

Updates labels to indicate phone number being optional. Corrects grammatical error in identity legend.
So content matches designs
Simple string updates

FBISCC-33: corrects text content for labels and legends

---

apps/fbis-ccf/behaviours/format-summary-locals.js
apps/fbis-ccf/fields/index.js
apps/fbis-ccf/index.js
apps/fbis-ccf/translations/src/en/fields.json
apps/fbis-ccf/translations/src/en/pages.json
apps/fbis-ccf/views/partials/maincontent-left.html
assets/scss/custom.scss
test/format-summary-locals.spec.js

First pass at the confirmation and editing page, using correct labels and section headings depending on the user's question topic and identity.
So that user's understand how the answers they are checking relate to the fields they entered them for.
Adds 'format-summary-locals' behaviour to supplement the default 'hof-behaviour-summary-page' behaviour with business logic specific to FBIS. 
Unit tests added for the new behaviour.

FBISCC-10: confirm and edit responses

---

apps/fbis-ccf/behaviours/add-uan-validator-if-required.js
apps/fbis-ccf/translations/src/en/validation.json
apps/fbis-ccf/validators/index.js
test/add-uan-validator-if-required.spec.js
test/validators.spec.js

Adds validation of UAN field
So that users can not submit a query if the UAN field is invalid, which would mean the SRC could not connect their query to an existing application.
Adds a custom validator to apps/fbiscc/validators/index.js
New unit tests added
If the field is empty:
If the input is invalid:

FBISCC-31: UAN validation

---

package-lock.json
package.json

Update to use Use HOF v17.3.1 
We want to use a cleaner logger and also use the latest version of hof.  More context below:
* Previously, the logging was quite noisey displaying gets and post requests without any context.
* The latest version of HOF includes a cleaner logger with gets and posts request with session ID providing some context
* The latest logger uses a combination of winston and morgan
* Future logging should follow the format
req.log(<log_level>, <msg1>, <msg2>, etc)
* A PR to update the HOF documention will be required to explain the logging.
* A future PR should update the FBIS ReadMe to point to this doc
* Can't see any value of adding any logging to what we have at the moment
* We will need to update kubernetes to use the right node environment for the various …

FBISCC-22 HOF v17.3.1 use cleaner logger

---

apps/fbis-ccf/behaviours/submit.js
test/behaviours/submit.spec.js

Adds logging for email success/failure when user submits the form.
So that the dev team are informed of whether the key email component of the application is working correctly and action if there are any issues.
Uses HOF's built in logger. Logs a success message and the email reference on success. Logs an error message, the email reference, and the error itself on failure.
Two new unit tests added to cover the logging. Some existing tests have been refactored to use more use-case like test data.

FBISCC-37: add logging to notify integration

---

index.js

Redirect from the base url to the landing page.
So that users do not see an error if the navigate to the base url for the service and can start their journey successfully.
Add middleware to the hof express app that redirects to the landing page if original url is base url.

FBISCC-46: redirect base url to landing page

---

kube/branch/ingress-internal.yaml
kube/dev/ingress-internal.yaml
kube/prod/ingress-external.yaml
kube/stg/ingress-internal.yaml
kube/uat/ingress-internal.yaml

Fix the following issue: In our environments we are unable to get to the baseurl without a path `https://fbis-contact-form.dev.internal.sas-notprod.homeoffice.gov.uk/` but this works `https://fbis-contact-form.dev.internal.sas-notprod.homeoffice.gov.uk/landing`
* Update ingress and remove the `ingress.kubernetes.io/app-root` annotation
* If the root of your application is / then you won't need this, see https://kubernetes.github.io/ingress-nginx/examples/rewrite/#deployment. Setting this to / will mean  visiting / will redirect to / causing an infinite loop.

FBISCC-46 Fix: baseurl not working without a path

---

.eslintrc
apps/fbis-ccf/behaviours/clear-session.js
apps/fbis-ccf/behaviours/submit.js
apps/fbis-ccf/index.js
assets/js/disable-multiple-submit.js
assets/js/index.js
config.js
lib/utils.js
package-lock.json
package.json
test/behaviours/submit.spec.js
test/lib/utils.spec.js

Prevent multiple submissions of the same query
So that the SRC does not receive duplicate emails for the same query
Client-side:
* `disable-multiple-submit` script in assets disables buttons on submit
Server-side (if client has JS disabled or removes client-side protection):
* `submit` behaviour stores the email reference on first submit, before send
* each submit checks if the reference exists on the session
* if reference exists, poll notify to check if the email has reached them and resolve accordingly
* poll is set to retry up to 5 times before failing
* poll failures are handled in the same was as an email failing on a single submit
* poll timeout is set to 1 second
* poll retry and timeout both set in config
Tests added for new `utils` functions (polling and getting email status …

FBISCC-47: prevent multiple form submission

---

assets/js/disable-multiple-submit.js
config.js

Refactor client-side prevention of multiple submits to throttle, rather than completely disable the submit button.
So that users are not prevented from submitting the form if the button is disabled on a false submit.
Revised client-side script to disable multiple submission. Now sets a 'throttle' data attribute on a timeout to prevent more than one submission per second. Has the added benefit of not using the disabled CSS class, so there is no jarring temporary style change when the page is submitted.

FBISCC-47: throttle multiple submits on client side

---

apps/fbis-ccf/fields/index.js

**What**
Updates maximum characters of customer query to 2000
**Why**
To be in line with designs
**How**
Simple argument change from 500 -> 2000 in fields/index validator for query

FBISCC-44 Change maximum character count of customer query to 2000

---

apps/fbis-ccf/fields/index.js
apps/fbis-ccf/translations/src/en/fields.json
test/ui/details/details.spec.js
test/ui/identity/identity.spec.js
test/ui/question/question.spec.js

Backfill test for identity and details pages.
To get automated assurance for this functionality.
Adds `identity.spec.js` and `details.spec.js` with automation tests for question page content and validation.

FBISCC-54: backfilling tests for identity and details pages

---

apps/fbis-ccf/translations/src/en/validation.json
test/ui/04 - query/character-count.spec.js
test/ui/04 - query/validation.spec.js
test/ui/ui-test-config.js

Backfill automation tests for query page validation. Includes query, name, email address, and UAN for both representative and applicant branches.
To provide automated assurance that the user is correctly prevented from submitting invalid fields and that they see the correct content depending on whether they are the applicant or a representative.
Adds `validation.spec.js` file in the test/ui/query folder

FBISCC-56: backfill automation tests for query page validation

---

test/ui/04 - query/validation.spec.js

Reorganise query page validation tests so they are grouped by requirement ids.
So that the output of test runs can be linked to the business requirements explicitly.

FBISCC-56: refactor query page validation tests with requirement ids

---

.gitignore
kube/branch/deployment.yaml
kube/dev/deployment.yaml
kube/prod/deployment.yaml
kube/stg/deployment.yaml
kube/uat/deployment.yaml

Add volumes to our kubernetes deployments
* Some users have experienced issues where the `bundle.js` file isn't showing the public folder in an app.  This is usually used for clientside js
* At its core, a volume is just a directory, possibly with some data in it, which is accessible to the containers in a pod
* Hopefully, this fixes the issue of bundle.js not showing in the various environments such as dev, uat etc
Used the branch feature but it was working even without this deployment script 🤷‍♂️

FBISCC-62 fix missing public files

---

test/ui/07 - feedback/feedback.spec.js
test/ui/ui-test-config.js

Add UI tests for Feedback page content, validation and sending feedback
To provide automated assurance that the user can view the feedback page and send feedback as expected
adds feedback.spec.js to the test/ui/feedback folder

FBISCC-17: add UI tests for feedback page

---

test/ui/04 - query/content.spec.js
test/ui/04 - query/validation.spec.js

Backfilling UI tests for query page text content.
To provide automated assurance that the user sees the correct headings, text fields, and labels based on their earlier selections.
Adds `content.spec.js` in the test/ui/query directory.

FBISCC-55: backfilling UI tests for query page text content

---

README.md

Add windows setup instructions to README
So that users without unix-like operating systems can run the service locally, e.g. test engineers who may be on different equipment than developers

docs: add windows setup instructions to README

---

.drone.yml
.gitignore
package-lock.json
package.json
sonar-project.properties

Add test execution and coverage reports after unit and UI test runs.
So that we can generate persistent reports in the sonar dashboard which can be used to inform and approve releases.
A test coverage report is generated in `coverage/lcov.info` after unit test runs using [nyc](https://www.npmjs.com/package/nyc). Execution reports are generated in the `executions` directory, with separate reports for unit tests and UI tests across three browsers. Execution reports are generated with the [mocha-sonar](https://www.npmjs.com/package/@danmasta/mocha-sonar) package.

FBISCC-60: add test execution and coverage reports

---

apps/fbis-ccf/validators/index.js

Amend UAN validation regular expression to protect against [regular expression denial of service attacks](https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS).
A sonar scan identified that the existing regular expression would be susceptible to this kind of attack.
Tested a new regex using ReDoS checkers to ensure that it is not vulnerable, while also testing with existing UAN validation unit test suite to ensure it meets the business requirements.

FBISCC-66: amend UAN regex to prevent ReDoS attacks

---

.eslintignore
.gitignore
package-lock.json
package.json
sonar-project.properties
test/reporter-config/chromium.json
test/reporter-config/firefox.json
test/reporter-config/unit.json
test/reporter-config/webkit.json

Add additional test execution reports in an HTML format 
So that QAT can review them when assuring releases, in addition to the reports held in the sonar dashboard.
Uses mocha-multi-reporter to generate multiple different report types on test runs.

FBISCC-60: additional text execution reports

---

apps/fbis-ccf/behaviours/clear-session.js
apps/fbis-ccf/index.js
apps/fbis-ccf/translations/src/en/pages.json
apps/fbis-ccf/views/complete.html
apps/fbis-ccf/views/partials/confirmation-alert.html
apps/fbis-ccf/views/partials/what-happens-next.html
apps/feedback/translations/src/en/pages.json
apps/feedback/views/feedback-submitted.html
apps/feedback/views/partials/confirmation-alert.html
assets/scss/custom.scss
test/ui/06 - complete/complete.spec.js
test/ui/07 - feedback/feedback-submitted.spec.js
test/unit/behaviours/clear-session.spec.js

Add new '/complete' and '/feedback-submitted' pages which are in line with design 
Added new templates, partials and styling
To be more in line with design
Added UI tests in '06 - complete' and '07 - feedback'. Added tests for 'clear-session' behaviour.

FBISCC-63: Add new complete and feedback submitted pages

---

apps/fbis-ccf/fields/index.js
apps/fbis-ccf/index.js
apps/fbis-ccf/translations/src/en/fields.json
apps/fbis-ccf/translations/src/en/pages.json
apps/fbis-ccf/translations/src/en/validation.json
apps/fbis-ccf/views/representative-details.html
assets/scss/custom.scss
test/ui/v2/05 - representative-details/content.spec.js
test/ui/v2/05 - representative-details/validation.spec.js

Updates '/representative-details' page to be in line with v5 designs.
To match designs that have been validated in research with users.
Update field labels to match new desired inputs. Add validation to new fields. Add conditional field labels for inside/outside UK routes.
Added content.spec and validation.spec to 05 - representative details folder

FBISCC-69: update designs for representative-details page

---

apps/common/translations/src/en/error.json
apps/common/views/error.html
test/ui/08 - confirm/confirm.spec.js
test/ui/10 - feedback/feedback.spec.js
test/ui/10 - feedback/submitted.spec.js
test/ui/11 - errors/problem-with-this-service.spec.js

Add page for any 500 error - service failure
To bring app in line with new designs
Edit content in `error` template
Add UI tests in `11 - errors`

FBISCC-76: add updated service failure page

---

apps/fbis-ccf/translations/src/en/validation.json

Correct empty email validation message in line with new designs
For consistency across the whole service
Remove conditional branch for email address validation so that it always shows the same message, regardless of whether the user is the applicant or a representative.

FBISCC-70: correct empty email validation message

---

index.js

Set the html language to English
When this is not specified it causes an accessibility issue as screen readers need to know which language to use
Add htmlLang attribute to res.locals in `index.js`

FBISCC-64: Add html lang attribute to locals

---

apps/common/translations/src/en/error.json
apps/common/views/error.html
apps/fbis-ccf/behaviours/submit.js
test/ui/08 - confirm/confirm.spec.js
test/ui/11 - errors/form-not-submitted.spec.js
test/unit/behaviours/submit.spec.js

Add custom error page for when the form fails to send
Add conditional rendering to the existing error page which is shown and hidden based on the sort of error
So the user knows their query has not been sent so they can contact by phone or redo the form
Add UI tests

FBISCC-83: add custom error page when form submission fails

---

apps/common/views/partials/validation-summary.html
apps/fbis-ccf/behaviours/set-radio-button-error-link.js
apps/fbis-ccf/index.js
test/unit/behaviours/set-radio-button-error-link.spec.js

Correct focus behaviour after validation errors on radio button fields.
So that keyboard users can more easily navigate to the radio button field where they have made an error.
Set the validation summary list hrefs to the first option in a radio button group, when the error relates to a radio button here.

FBISCC-85: correct focus behaviour after radio button validation error

---

package-lock.json

Update character count to use commas when count is 1000 or more.
So that screen readers correctly read the count as a number, not a year
Use latest version of hof-frontend-toolkit

FBISCC-87: fix screen readers reading character count as a year

---

apps/fbis-ccf/translations/src/en/pages.json
apps/fbis-ccf/views/confirm.html

Update change link aria labels in line with content design input
So that screen reader users are aware which field each link will change
Add translations for aria-labels, remove all plain text strings in `confirm.html` and replace with new aria-labels.

FBISCC-88: update change link aria-labels after content design input

---

config.js
index.js
kube/branch/configmap.yaml
kube/dev/configmap.yaml
kube/prod/configmap.yaml
kube/stg/configmap.yaml
kube/uat/configmap.yaml

Set CORS header to origin
Gets origin from configmap in each environment, sets it to an env var and sets the CORS header to it in `index.js`
To prevent web browser data loading

FBISCC-84: set CORS header to origin

---

apps/common/views/partials/validation-summary.html

Improve screen reader usability on error screens
So that screen reader users have the same information available to them as non screen reader users.
Make error summary list aria-labelledby the 'There is a problem' header, give summary list role alert.

FBISCC-85: add role alert to error summary list for screen readers

---

apps/fbis-ccf/fields/index.js
apps/fbis-ccf/translations/src/en/validation.json
package-lock.json
test/ui/04 - applicant-details/validation.spec.js
test/ui/05 - representative-details/validation.spec.js
test/ui/06 - contact-details/contact-details.spec.js

Add new 'notUrl' validator to name fields and 'numeric' validator to phone field to ensure no malicious information can be provided. Add new translation for the new validation errors.
The security architects from the ITHC raised concern that malicious links could be provided in the name columns to trick users or caseworkers into clicking on them. This fix ensures this cannot happen.
New notUrl validator doesn't allow links to be provided in the name fields. Numeric validator on phone also ensures links can't be provided
Added UI tests for the new validation errors that arise.

FBISCC-113: More control over user supplied input

---

apps/fbis-ccf/fields/index.js
apps/fbis-ccf/translations/src/en/validation.json
package-lock.json

Update hof-form-controller version to capture fixed phone validator, remove old validator from phone field.
To allow us to validate for phone numbers

FBISCC-113: Update phone validator and translations for error message

---

apps/feedback/behaviours/clear-feedback.js
test/unit/behaviours/clear-feedback.spec.js

Amended behaviour where feedBackEmailReference was cleared after every email send, now clears when the user returns to the form
Ammended clear-feedback-spec to reflect this change
A user was able to spam post requests to the API to flood the CCF inbox with emails. Amending this behaviour means that each session will only be able to send one email per feedback session

FBISCC-114

---

apps/fbis-ccf/behaviours/add-location-to-backlink.js
apps/fbis-ccf/behaviours/add-uan-validator-if-required.js
apps/fbis-ccf/behaviours/disable-backlink-on-edit.js
apps/fbis-ccf/behaviours/handle-identity-change.js
apps/fbis-ccf/behaviours/handle-question-change.js
apps/fbis-ccf/index.js
apps/fbis-ccf/translations/src/en/fields.json
apps/fbis-ccf/translations/src/en/validation.json
test/ui/04 - applicant-details/content.spec.js
test/ui/04 - applicant-details/validation.spec.js
test/ui/08 - confirm/confirm.spec.js
test/unit/behaviours/add-uan-validator-if-required.spec.js
test/unit/behaviours/handle-identity-change.spec.js
test/unit/behaviours/handle-question-change.spec.js

Adds 'required' validator to UAN when required.
Collects UAN when question category is changed
Removes back link from details pages after question category or identity is changed

FBISCC-156: make UAN required and update tests

---

apps/fbis-ccf/translations/src/en/fields.json
test/ui/06 - contact-details/contact-details.spec.js

Edit hint text on contact details fields to match new design
Update tests

FBISCC-159: add hint text to fields on contact details page
